theme: jekyll-theme-tactile
title: Persing Analytics
description: Jeremy Persing's analytics projects and portfolio. Here you will find details about projects I've worked on and content about data and analytics.
